# .github/workflows/terraform.yml
name: Terraform

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.0.0"

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Init
      run: |
        cd environments/prod
        terraform init

    - name: Terraform Plan
      run: |
        cd environments/prod
        terraform plan -var-file="variables.tfvars"
      if: github.event_name == 'pull_request'

    - name: Terraform Apply
      run: |
        cd environments/prod
        terraform apply -auto-approve -var-file="variables.tfvars"
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'